### ISSUE TITLE
Failed to start ShuffleWorker

### ISSUE THREAD

**Issue by dangshazi** [flink-extended/flink-remote-shuffle#42]
# Error Message
`2022-03-01 16:46:33,521 WARN  [main-SendThread(10.X.X.X:2181)] org.apache.flink.shaded.zookeeper3.org.apache.zookeeper.ClientCnxn [] - Session 0x0 for server 10.130.13.114/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect
java.lang.IllegalArgumentException: Unable to canonicalize address 10.130.13.114/<unresolved>:2181 because it's not resolvable
        at org.apache.flink.shaded.zookeeper3.org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:65) ~[shuffle-dist-1.0.0.jar:?]
        at org.apache.flink.shaded.zookeeper3.org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:41) ~[shuffle-dist-1.0.0.jar:?]
        at org.apache.flink.shaded.zookeeper3.org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1001) ~[shuffle-dist-1.0.0.jar:?]
        at org.apache.flink.shaded.zookeeper3.org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) [shuffle-dist-1.0.0.jar:?]`

# JDK
`openjdk 15.0.1 2020-10-20
OpenJDK Runtime Environment (build 15.0.1+9-18)
OpenJDK 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)`

**Comment by wsry** [comment]
Thanks for reporting this issue, we will take a look.

**Comment by wsry** [comment]
This issue seems relate to JDK version and Zookeeper version.  I already merged a fix to the main branch. The fix upgraded the zookeeper version to 3.5.9. @dangshazi Could you help to test if the fix solves your problem?

**Comment by wsry** [comment]
As discussed offline, this issue has been resolved, closing this issue.
